In [30]:
import pandas as pd
import numpy as np

In [53]:
genre_data = pd.read_csv("Resources/Media Library.csv")
genre_df = pd.DataFrame(genre_data)
genre_df = genre_df[['🎦  ID','🎯  TAG Music Styles (from 🎥 Films)']]
genre_df = genre_df.rename(columns={'🎦  ID':"ID",'🎯  TAG Music Styles (from 🎥 Films)':"genre"})
# remove space after comma
genre_df['genre'] = genre_df['genre'].str.replace(r'([ ]*,[ ]+)',",")
genre_df['genre'] = genre_df['genre'].str.strip()
# add PRO to beginning of program ID
genre_df['ID'] = 'PRO_' + genre_df['ID']
genre_split = genre_df['genre'].str.split(pat=',', expand=True)
genre_split


C:\Users\Peter Nguyen\AppData\Local\Temp\ipykernel_16980\476088216.py:6: FutureWarning: The default value of regex will change from True to False in a future version.
  genre_df['genre'] = genre_df['genre'].str.replace(r'([ ]*,[ ]+)',",")


0                  1         2     3     4     5     6     7
0             Piano  CONTEMPORARY JAZZ      None  None  None  None  None  None
1        VOCAL JAZZ               JAZZ      SOUL  None  None  None  None  None
2        VOCAL JAZZ               JAZZ      SOUL  None  None  None  None  None
3        VOCAL JAZZ               JAZZ      SOUL  None  None  None  None  None
4              JAZZ     SPIRITUAL JAZZ      None  None  None  None  None  None
...             ...                ...       ...   ...   ...   ...   ...   ...
2501       ROMANTIC           SYMPHONY  CONCERTO  None  None  None  None  None
2502      CLASSICAL           SYMPHONY      None  None  None  None  None  None
2503       ROMANTIC              OPERA      None  None  None  None  None  None
2504      CLASSICAL           SYMPHONY      None  None  None  None  None  None
2505  IMPRESSIONISM       CONTEMPORARY      None  None  None  None  None  None

[2506 rows x 8 columns]

In [54]:
# replace none with np.nan
genre_split = genre_split.fillna(value=np.nan)
# We are going to work backwards from least filled column to most filled column (7-1)

# Column 7
genre_split[7].unique()
# column contains nan and 'New Style', we can just drop this column
genre_split = genre_split.drop([7])

In [55]:
#column 6
genre_split[6].unique()
genre_split[6] = genre_split[6].replace('TOPROCK', 'ROCK')
genre_split[6] = genre_split[6].replace('NEW STYLE', np.nan)

#Check
genre_split[6].unique()


array([nan, 'SOUL', 'TOPROCK', 'NEW STYLE'], dtype=object)

In [56]:
# Column 5
genre_split[5].unique()
genre_split[5] = genre_split[5].replace('JAZZ FUSION', 'JAZZ')
genre_split[5] = genre_split[5].replace('CHARANGA', 'DANCE,ETHNIC,LATINO')
genre_split[5] = genre_split[5].replace('INDIE POP', 'INDIE,POP')
genre_split[5] = genre_split[5].replace('BREAKDANCE', 'DANCE')
genre_split[5] = genre_split[5].replace('NEW WAVE', np.nan)
genre_split[5] = genre_split[5].replace('RAP / HIP-HOP', 'RAP,HIP-HOP')

# Check
genre_split[5].unique()

array([nan, 'JAZZ FUSION', 'ROCK', 'CHARANGA', 'RHYTHM AND BLUES',
       'INDIE POP', 'BREAKDANCE', 'RAP / HIP-HOP', 'NEW WAVE'],
      dtype=object)

In [48]:
# Column 4
genre_split[4].unique()
genre_split[4] = genre_split[4].replace('CROSSOVER JAZZ', 'JAZZ')
genre_split[4] = genre_split[4].replace('CONTEMPORARY JAZZ', 'JAZZ')
genre_split[4] = genre_split[4].replace('BEBOP', 'JAZZ')
genre_split[4] = genre_split[4].replace('CENTRAL AFRICAN MUSIC', 'AFRICAN,ETHNIC')
genre_split[4] = genre_split[4].replace('GLOBAL MUSIC / WORLD MUSIC', 'ETHNIC')
genre_split[4] = genre_split[4].replace('MANDINKA MUSIC', 'INDIE,ROCK')
genre_split[4] = genre_split[4].replace('AVANT-GARDE JAZZ', 'JAZZ')
genre_split[4] = genre_split[4].replace('SCANDINAVIAN JAZZ', 'JAZZ,ETHNIC,EUROPEAN')
genre_split[4] = genre_split[4].replace('INDIE POP', 'INDIE,POP')
genre_split[4] = genre_split[4].replace('SWING', 'JAZZ')
genre_split[4] = genre_split[4].replace('JAZZ FUNK', 'JAZZ,FUNK')
genre_split[4] = genre_split[4].replace('ROCK FUSION', 'ROCK')
genre_split[4] = genre_split[4].replace('STRAIGHT JAZZ', 'JAZZ')
genre_split[4] = genre_split[4].replace('ETHNO-JAZZ', 'JAZZ,ETHNIC')
genre_split[4] = genre_split[4].replace('TIMBA', 'RHYTHM AND BLUES,ETHNIC,LATINO')
genre_split[4] = genre_split[4].replace('ELECTRONIC MUSIC', 'ELECTRONIC')
genre_split[4] = genre_split[4].replace('DEEP HOUSE', 'ELECTRONIC')
genre_split[4] = genre_split[4].replace('RUMBA CONGOLAISE', 'AFRICAN,ETHNIC,DANCE')
genre_split[4] = genre_split[4].replace('SYNTH-POP', 'ELECTRONIC,POP')
genre_split[4] = genre_split[4].replace('ELECTRONICA', 'ELECTRONIC')
genre_split[4] = genre_split[4].replace('HOUSE', 'ELECTRONIC')
genre_split[4] = genre_split[4].replace('ELECTRO', 'ELECTRONIC')
genre_split[4] = genre_split[4].replace('NEW WAVE', np.nan)
genre_split[4] = genre_split[4].replace('HIGHLIFE', 'JAZZ,ETHNIC,AFRICAN')
genre_split[4] = genre_split[4].replace('EXPERIMENTAL MUSIC', np.nan)
genre_split[4] = genre_split[4].replace('BIG BAND', 'JAZZ')
genre_split[4] = genre_split[4].replace('RAP / HIP-HOP', 'RAP,HIP-HOP')


array([nan, 'CROSSOVER JAZZ', 'CONTEMPORARY JAZZ', 'BEBOP',
       'CENTRAL AFRICAN MUSIC', 'GLOBAL MUSIC / WORLD MUSIC', 'SOUL',
       'MANDINKA MUSIC', 'AVANT-GARDE JAZZ', 'SCANDINAVIAN JAZZ',
       'INDIE POP', 'SWING', 'CLASSICAL', 'POP', 'JAZZ FUNK',
       'ROCK FUSION', 'STRAIGHT JAZZ', 'ETHNO-JAZZ', 'TIMBA',
       'ELECTRONIC MUSIC', 'DEEP HOUSE', 'RUMBA CONGOLAISE', 'BLUES',
       'SYNTH-POP', 'ELECTRONICA', 'AMBIENT', 'ALTERNATIVE', 'DANCE',
       'HOUSE', 'ELECTRO', 'NEW WAVE', 'PUNK', 'HIGHLIFE',
       'RAP / HIP-HOP', 'EXPERIMENTAL MUSIC', 'BIG BAND'], dtype=object)

In [49]:
# Column 3
genre_split[3].unique()
genre_split[3] = genre_split[3].replace('Saxophone', 'JAZZ,INSTRUMENTAL')
genre_split[3] = genre_split[3].replace('Guitar', 'INSTRUMENTAL')
genre_split[3] = genre_split[3].replace('CLASSICAL CROSSOVER', 'CLASSICAL')
genre_split[3] = genre_split[3].replace('BEBOP', 'JAZZ')
genre_split[3] = genre_split[3].replace('CONTEMPORARY JAZZ', 'JAZZ')
genre_split[3] = genre_split[3].replace('VOCAL JAZZ', 'JAZZ')
genre_split[3] = genre_split[3].replace('SOUL JAZZ', 'JAZZ,SOUL')
genre_split[3] = genre_split[3].replace('GLOBAL MUSIC / WORLD MUSIC', 'ETHNIC')
genre_split[3] = genre_split[3].replace("N'goni", 'ETHNIC,AFRICAN,INSTRUMENTAL')
genre_split[3] = genre_split[3].replace('SPIRITUAL JAZZ', 'JAZZ')
genre_split[3] = genre_split[3].replace('MODAL JAZZ', 'JAZZ')
genre_split[3] = genre_split[3].replace('STRAIGHT JAZZ', 'JAZZ')
genre_split[3] = genre_split[3].replace('FREE JAZZ', 'JAZZ')
genre_split[3] = genre_split[3].replace('SWING', 'JAZZ')
genre_split[3] = genre_split[3].replace('AVANT-GARDE JAZZ', 'JAZZ')
genre_split[3] = genre_split[3].replace('ETHNO-JAZZ', 'JAZZ,ETHNIC')
genre_split[3] = genre_split[3].replace('JAZZ FUSION', 'JAZZ')
genre_split[3] = genre_split[3].replace('KLEZMER MUSIC', 'INSTRUMENTAL,ETHNIC,EUROPEAN')
genre_split[3] = genre_split[3].replace('MUSETTE', 'INSTRUMENTAL,ETHNIC,EUROPEAN,DANCE')
genre_split[3] = genre_split[3].replace('BIG BAND', 'JAZZ')
genre_split[3] = genre_split[3].replace('AFRO-POP / AFROBEATS', 'POP,AFRICAN')
genre_split[3] = genre_split[3].replace('JAZZ ROCK', 'JAZZ,ROCK')
genre_split[3] = genre_split[3].replace('CARIBBEAN MUSIC', 'ETHNIC,CARIBBEAN')
genre_split[3] = genre_split[3].replace('JAZZ FUNK', 'JAZZ,FUNK')
genre_split[3] = genre_split[3].replace('EXPERIMENTAL MUSIC', np.nan)
genre_split[3] = genre_split[3].replace('INSTRUMENTAL HIP-HOP', 'INSTRUMENTAL,HIP-HOP')
genre_split[3] = genre_split[3].replace('ALTERNATIVE HIP-HOP', 'ALTERNATIVE,HIP-HOP')
genre_split[3] = genre_split[3].replace('INDIE POP', 'INDIE,POP')
genre_split[3] = genre_split[3].replace('FREE FUNK', 'FUNK')
genre_split[3] = genre_split[3].replace('ROCK FUSION', 'ROCK')
genre_split[3] = genre_split[3].replace('SKA', 'ETHNIC,CARIBBEAN')
genre_split[3] = genre_split[3].replace('POP ROCK', 'POP,ROCK')
genre_split[3] = genre_split[3].replace('HARD BOP', 'JAZZ')
genre_split[3] = genre_split[3].replace('CROSSOVER JAZZ', 'JAZZ')
genre_split[3] = genre_split[3].replace('TRANCE', 'ELECTRONIC,DANCE')
genre_split[3] = genre_split[3].replace('BOLERO', 'DANCE,ETHNIC,LATINO')
genre_split[3] = genre_split[3].replace('RUMBA', 'DANCE,ETHNIC,LATINO')
genre_split[3] = genre_split[3].replace('LATIN', 'ETHNIC,LATINO')
genre_split[3] = genre_split[3].replace('MPB', 'POP,ETHNIC,LATINO')
genre_split[3] = genre_split[3].replace('INDIE FOLK', 'INDIE')
genre_split[3] = genre_split[3].replace('BROKE BEAT', 'ELECTRONIC,JAZZ,RHYTHM AND BLUES')
genre_split[3] = genre_split[3].replace('WEST AFRICAN MUSIC', 'ETHNIC,AFRICAN')
genre_split[3] = genre_split[3].replace('JAZZ RAP', 'JAZZ,RAP')
genre_split[3] = genre_split[3].replace('ELECTROPOP', 'ELECTRONIC,POP')
genre_split[3] = genre_split[3].replace('ELECTRONIC MUSIC', 'ELECTRONIC')
genre_split[3] = genre_split[3].replace('INDUSTRIAL', 'ELECTRONIC,ROCK,PUNK')
genre_split[3] = genre_split[3].replace('FUTURE BASS', 'ELECTRONIC,DANCE')
genre_split[3] = genre_split[3].replace('DISCO HOUSE', 'ELECTRONIC,DISCO')
genre_split[3] = genre_split[3].replace('ETHNOTRONICA', 'ELECTRONIC,ETHNIC')


genre_split[3] = genre_split[3].replace('CENTRAL AFRICAN MUSIC', 'AFRICAN,ETHNIC')
genre_split[3] = genre_split[3].replace('MANDINKA MUSIC', 'INDIE,ROCK')
genre_split[3] = genre_split[3].replace('SCANDINAVIAN JAZZ', 'JAZZ,ETHNIC,EUROPEAN')
genre_split[3] = genre_split[3].replace('ETHNO-JAZZ', 'JAZZ,ETHNIC')
genre_split[3] = genre_split[3].replace('TIMBA', 'RHYTHM AND BLUES,ETHNIC,LATINO')
genre_split[3] = genre_split[3].replace('ELECTRONIC MUSIC', 'ELECTRONIC')
genre_split[3] = genre_split[3].replace('DEEP HOUSE', 'ELECTRONIC')
genre_split[3] = genre_split[3].replace('RUMBA CONGOLAISE', 'AFRICAN,ETHNIC,DANCE')
genre_split[3] = genre_split[3].replace('SYNTH-POP', 'ELECTRONIC,POP')
genre_split[3] = genre_split[3].replace('ELECTRONICA', 'ELECTRONIC')
genre_split[3] = genre_split[3].replace('HOUSE', 'ELECTRONIC')
genre_split[3] = genre_split[3].replace('ELECTRO', 'ELECTRONIC')
genre_split[3] = genre_split[3].replace('NEW WAVE', np.nan)
genre_split[3] = genre_split[3].replace('HIGHLIFE', 'JAZZ,ETHNIC,AFRICAN')

array([nan, 'JAZZ', 'Saxophone', 'Guitar', 'SOUL', 'CLASSICAL CROSSOVER',
       'BEBOP', 'CONTEMPORARY JAZZ', 'VOCAL JAZZ', 'SOUL JAZZ',
       'GLOBAL MUSIC / WORLD MUSIC', "N'goni", 'BLUES', 'SPIRITUAL JAZZ',
       'MODAL JAZZ', 'STRAIGHT JAZZ', 'FREE JAZZ', 'SWING', 'ETHNO-JAZZ',
       'AVANT-GARDE JAZZ', 'JAZZ FUSION', 'RHYTHM AND BLUES',
       'KLEZMER MUSIC', 'MUSETTE', 'BIG BAND', 'AFRO-POP / AFROBEATS',
       'RAP / HIP-HOP', 'JAZZ ROCK', 'CARIBBEAN MUSIC', 'JAZZ FUNK',
       'EXPERIMENTAL MUSIC', 'INSTRUMENTAL HIP-HOP',
       'ALTERNATIVE HIP-HOP', 'DISCO', 'POP', 'FUNK', 'INDIE POP',
       'FREE FUNK', 'ROCK FUSION', 'SKA', 'POP ROCK', 'HARD BOP',
       'CROSSOVER JAZZ', 'TRANCE', 'BOLERO', 'RUMBA', 'ROCK',
       'LATIN MUSIC', 'MPB', 'INDIE FOLK', 'BROKEN BEAT',
       'WEST AFRICAN MUSIC', 'JAZZ RAP', 'ELECTROPOP', 'ELECTRONIC MUSIC',
       'INDUSTRIAL', 'FUTURE BASS', 'DISCO HOUSE', 'ETHNOTRONICA',
       'BOOGIE-FUNK', 'ELECTRO HOUSE', 'INDIE', 'PUNK', 'HOUSE',

In [50]:
# Column 2
genre_split[2].unique()

array([nan, 'SOUL', 'VOCAL JAZZ', 'JAZZ', 'CONTEMPORARY JAZZ', 'JAZZ RAP',
       'SOUL JAZZ', 'JAZZ FUNK', 'Piano', 'LATIN JAZZ', 'HARD BOP',
       'SOUTH AFRICAN MUSIC', 'JAZZ FUSION', 'ETHNO-JAZZ',
       'CLASSICAL CROSSOVER', 'SWING', 'COOL JAZZ / WEST COAST JAZZ',
       'STRAIGHT JAZZ', 'RAP / HIP-HOP', 'SPIRITUAL JAZZ',
       'GLOBAL MUSIC / WORLD MUSIC', 'CLASSICAL', 'RHYTHM AND BLUES',
       'FREE JAZZ', 'CONTEMPORARY', 'Guitar', 'MANDINKA MUSIC',
       'Saxophone', 'BOSSA-JAZZ', 'BIG BAND', 'SAMBA', 'Cello',
       'AFRO-CUBAN JAZZ', 'ELECTRO JAZZ / NU-JAZZ', 'EXPERIMENTAL POP',
       'POST-BOP', 'P-FUNK', 'FOLK', 'JAZZ ROCK', 'ORCHESTRA', 'BEBOP',
       'AVANT-GARDE JAZZ', 'NEGRO SPIRITUALS & CHRISTIAN MUSIC',
       'KLEZMER MUSIC', 'CROSSOVER JAZZ', 'GNAWA MUSIC', 'AFROBEAT',
       'TANGO', 'SPOKEN WORD / SLAM', 'LATIN ROCK', 'ORIENTAL JAZZ',
       'POP', 'MPB', 'LATIN POP', 'KLEZMER JAZZ', 'ROCK FUSION',
       'CONSCIOUS HIP HOP', 'CARIBBEAN MUSIC', 'FUNK', 'IND

In [51]:
# Column 1
genre_split[1].unique()

array(['CONTEMPORARY JAZZ', 'JAZZ', 'SPIRITUAL JAZZ',
       'EAST AFRICAN MUSIC', 'STRAIGHT JAZZ',
       'GLOBAL MUSIC / WORLD MUSIC', 'ARABIC MUSIC', 'CONSCIOUS HIP HOP',
       'R&B', nan, 'LATIN MUSIC', 'NEO SOUL', 'ELECTRO JAZZ / NU-JAZZ',
       'SOUL', 'AMERICANA', 'GYPSY JAZZ', 'BLUES', 'Saxophone',
       'JAZZ FUSION', 'AFRO-CUBAN JAZZ', 'RHYTHM AND BLUES', 'JAZZ FUNK',
       'Trumpet', 'ETHNO-JAZZ', 'JAZZ ROCK', 'Piano', 'ETHNOTRONICA',
       'CLASSICAL', 'FUNK', 'SWING', 'POP', 'AVANT-GARDE JAZZ',
       'WEST AFRICAN MUSIC', 'BALLET', 'FOLK', 'MODAL JAZZ', 'AFROBEAT',
       'Accordion', 'SAMBA', 'VOCAL JAZZ', 'POP ROCK', 'SOUL JAZZ',
       'GOSPEL', 'LATIN JAZZ', 'BLUES ROCK', 'Harmonica',
       'COOL JAZZ / WEST COAST JAZZ', 'BEBOP', 'POST-BOP', 'KLEZMER JAZZ',
       'AMBIENT', 'CROSSOVER JAZZ', 'LATIN POP', 'HARD BOP', 'MALOYA',
       'FREE JAZZ', 'ROCK', 'Guitar', 'JAZZ BLUES', 'BOSSA NOVA',
       'RAP / HIP-HOP', 'CARIBBEAN MUSIC', 'LATIN ROCK',
       'SOUTH 

In [52]:
# Column 0
genre_split[0].unique()

array(['Piano', 'VOCAL JAZZ', 'JAZZ', 'GLOBAL MUSIC / WORLD MUSIC',
       'GYPSY MUSIC', 'SOUL JAZZ', 'CONTEMPORARY JAZZ', 'FLAMENCO',
       'ORIENTAL JAZZ', 'SPOKEN WORD / SLAM', 'SPIRITUAL JAZZ',
       'JAZZ FUNK', nan, 'RAP / HIP-HOP', 'FADO', 'Trumpet', 'AMBIENT',
       'NEO SOUL', 'JAZZ ROCK', 'SEMBA', 'Guitar', 'STRAIGHT JAZZ',
       'SOUL', 'FUNK', 'BOSSA NOVA', 'SOUTH AFRICAN MUSIC', 'LATIN JAZZ',
       'FILM MUSIC', 'JAZZ FUSION', 'ORCHESTRA', 'SWING', 'POP',
       'MODAL JAZZ', 'MANDINKA MUSIC', 'DANCE', 'ARABIC MUSIC', 'BLUES',
       'Saxophone', 'TOUAREG MUSIC', 'WEST AFRICAN MUSIC', 'Tabla',
       'SAMBA', 'FREE JAZZ', 'MPB', 'Turntables', 'GYPSY JAZZ', 'ROCK',
       'AFRO-CUBAN JAZZ', 'COOL JAZZ / WEST COAST JAZZ',
       'AVANT-GARDE JAZZ', 'HARD BOP', 'MAKOSSA', 'GOSPEL', 'BEBOP',
       'POST-BOP', 'Clarinet', 'ETHIO-JAZZ', 'LATIN MUSIC', 'GNAWA MUSIC',
       'AFROBEAT', 'MALOYA', 'COUNTRY', 'REGGAE', 'CUMBIA', 'MORNA',
       'SALSA', 'CLASSICAL INDIAN MUSI